export interface Course {
  Change: string;
  Class: '不分班' | '全英班' | '甲班' | '乙班';
  CompulsoryElective: string;
  Context: string;
  Credit: string;
  Department: string;
  Description: string;
  EMI: string;
  Friday: string;
  Grade: string;
  Monday: string;
  MultipleCompulsory: string;
  Name: string;
  Number: string;
  Programs: string;
  Remaining: string;
  Restrict: string;
  Room: string;
  Saturday: string;
  Select: string;
  Selected: string;
  Sunday: string;
  Teacher: string;
  Thursday: string;
  Tuesday: string;
  Url: string;
  Wednesday: string;
  YearSemester: string;
}
