name: Manual GH-Pages Deployment

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type YES to deploy'
        required: true
        default: 'NO'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm == 'YES' }}
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Run Deployment Script
        run: |
          echo "Deploying gh-pages branch..."
          # Add your deployment commands here
